site_name: CMS Tier 3 at University of Notre Dame
site_url: https://crcresearch.github.io/ndcmsT3/
repo_url: https://github.com/crcresearch/ndcmsT3

theme:
  name: readthedocs
  logo: images/cms_logo.png

extra_css:
  - css/custom.css

# Navigation bar to be updated upon new pages
nav:
  - HOME: index.md
  - RESOURCES:
    - NDCMS: resources/ndcms.md
    - CAML: resources/caml.md
  - APPLICATIONS:
    - EFT: apps/eft.md
    - DV5: apps/dv5.md
    

# Enable git revision date from git history
plugins:
  - search
  - git-revision-date-localized:
      type: date
      enable_creation_date: true
      fallback_to_build_date: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - footnotes