name: Documentation CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed for gh-deploy
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important for git revision dates

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs \
                      mkdocs-git-revision-date-localized-plugin \
                      pymdown-extensions

      - name: Deploy documentation
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          mkdocs gh-deploy --force